version: '3.7'

services:
  app:
    container_name: nsa-dev
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/nsa'
      - '/nsa/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true 
  
  